# -*- coding: utf-8 -*-
"""CluMap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rGrX86vykmDyLJdf6q8iFfSB9UjWAF6P
"""


import folium
from folium.plugins import MarkerCluster
import pandas as pd

data = pd.read_csv('/content/drive/My Drive/SWAPP/data_cleansed_final.csv', encoding='utf-8', header=0)

#클러스터링 된 그룹 라벨
label= pd.read_csv('/content/drive/My Drive/SWAPP/birch_labels.csv', names = ['cluster_label'], encoding='utf-8', header=0)

data = pd.concat([data, label], axis = 1)


m = folium.Map(location=[36.3, -107.5], zoom_start=3)

mcg = folium.plugins.MarkerCluster(control=False)
m.add_child(mcg)
group = []
max = 0

#모든 데이터를 넣으면 동작하지 못함, 무작위 표본 4%를 사용한다.
for i in range(0, len(data), 25):
    num = data.loc[i, 'cluster_label']
    if num == -1: #클러스터에 속하지 못한 그룹은 제외
        continue
    if num > max:
        for j in range(max, num + 1): #새로운 클러스터 그룹이 발견된다면, 새로운 그룹 생성 후 마커 추가
            group.append(folium.plugins.FeatureGroupSubGroup(mcg, 'group' + str(j + 1)))
            m.add_child(group[j])
        max = num + 1
    latitude = data.loc[i, 'latitude']
    longitude = data.loc[i, 'longitude']
    folium.Marker([latitude, longitude]).add_to(group[num-1])

folium.LayerControl(collapsed=False).add_to(m)
